// BACKEND HAUT

import {
  MediaItemWithOwner,
  UserWithNoPassword,
  MediaItem,
  Like,
  Comment,
  TagResult,
  Tag,
} from 'hybrid-types/DBTypes';
import {useState, useEffect} from 'react';
import {fetchData} from '../lib/functions';
import {Credentials, RegisterCredentials} from '../types/LocalTypes';
import {
  AvailableResponse,
  LoginResponse,
  MessageResponse,
  UploadResponse,
  UserResponse,
} from 'hybrid-types/MessageTypes';

// MEDIAN KÄYTTÖ

const useMedia = (id?: number) => {
  const [mediaArray, setMediaArray] = useState<MediaItemWithOwner[]>([]);
  const url = id ? '/media/byuser/' + id : '/media';

  useEffect(() => {
    const getMedia = async () => {
      try {
        const media = await fetchData<MediaItemWithOwner[]>(
          process.env.EXPO_PUBLIC_MEDIA_API + url,
        );

        const mediaWithOwner: MediaItemWithOwner[] = await Promise.all(
          media.map(async (item) => {
            const owner = await fetchData<UserWithNoPassword>(
              process.env.EXPO_PUBLIC_AUTH_API + '/users/' + item.user_id,
            );

            const mediaItem: MediaItemWithOwner = {
              ...item,
              username: owner.username,
            };

            return mediaItem;
          }),
        );

        setMediaArray(mediaWithOwner);
      } catch (error) {
        console.error((error as Error).message);
      }
    };

    getMedia();
  }, []);

  const postMedia = async (
    file: UploadResponse,
    inputs: Record<string, string>,
    token: string,
  ) => {
    console.log('post media token:', token);
    // TODO: create a suitable object for Media API, the type is MediaItem without media_id, user_id, thumbnail and created_at. All those are generated by the API.
    const mediaObject: Omit<
      MediaItem,
      'media_id' | 'user_id' | 'thumbnail' | 'screenshots' | 'created_at'
    > = {
      title: inputs.title,
      description: inputs.description,
      filename: file.data.filename,
      media_type: file.data.media_type,
      filesize: file.data.filesize,
    };
    // post the data to Media API and get the data as MessageResponse
    const options = {
      method: 'POST',
      headers: {
        Authorization: 'Bearer ' + token,
        'Content-type': 'application/json',
      },
      body: JSON.stringify(mediaObject),
    };
    // TODO: return the data
    return await fetchData<MessageResponse>(
      process.env.EXPO_PUBLIC_MEDIA_API + url,
      options,
    );
  };
  return {mediaArray, postMedia};
};

// FILE

const useFile = () => {
  const postFile = async (file: File, token: string) => {
    console.log('post file token:', token);
    // create FormData object
    const formData = new FormData();
    // add file to FormData
    formData.append('file', file);
    // upload the file to file server and get the file data POST
    const options = {
      method: 'POST',
      headers: {Authorization: 'Bearer ' + token},
      body: formData,
    };
    // return the file data. The type is UploadResponse
    return await fetchData<UploadResponse>(
      process.env.EXPO_PUBLIC_UPLOAD_API + '/upload',
      options,
    );
  };
  return {postFile};
};

// AUTENTIKOINTI

const useAuthentication = () => {
  // kirjautuminen
  const postLogin = async (credentials: Credentials) => {
    const options = {
      method: 'POST',
      body: JSON.stringify(credentials),
      headers: {'Content-Type': 'application/json'},
    };
    try {
      return await fetchData<LoginResponse>(
        process.env.EXPO_PUBLIC_AUTH_API + '/auth/login',
        options,
      );
    } catch (error) {
      throw new Error((error as Error).message);
    }
  };

  return {postLogin};
};

// KÄYTTÄJÄ

const useUser = () => {
  // hae käyttäjä ! huom! vaikka get -> tarvitaan options, koska taarvitaan headersiin bearer
  const getUserByToken = async (token: string) => {
    const options = {
      headers: {Authorization: 'Bearer ' + token},
    };
    return await fetchData<UserResponse>(
      process.env.EXPO_PUBLIC_AUTH_API + '/users/token',
      options,
    );
  };

  // rekisteröinti
  const postRegister = async (credentials: RegisterCredentials) => {
    const options = {
      method: 'POST',
      body: JSON.stringify(credentials),
      headers: {'Content-Type': 'application/json'},
    };
    console.log(credentials);
    try {
      return await fetchData<UserResponse>(
        process.env.EXPO_PUBLIC_AUTH_API + '/users',
        options,
      );
    } catch (error) {
      console.error(error);
      // throw new Error((error as Error).message);
    }
  };

  // NIMI & EMAIL AVAILABLE
  const getUsernameAvailable = async (username: string) => {
    return await fetchData<AvailableResponse>(
      process.env.EXPO_PUBLIC_AUTH_API + '/users/username/' + username,
    );
  };

  const getEmailAvailable = async (email: string) => {
    // fetch from endpoint /users/email/:email
    return await fetchData<AvailableResponse>(
      process.env.EXPO_PUBLIC_AUTH_API + '/users/email/' + email,
    );
  };

  const getUserById = async (id: number) => {
    return await fetchData<UserWithNoPassword>(
      process.env.EXPO_PUBLIC_AUTH_API + '/users/' + id,
    );
  };
  return {
    getUserByToken,
    postRegister,
    getUsernameAvailable,
    getEmailAvailable,
    getUserById,
  };
};

// TYKKÄYKSET
const useLike = () => {
  const postLike = async (media_id: number, token: string) => {
    // TODO: Send a POST request to /likes with object { media_id } and the token in the Authorization header.
    const options = {
      method: 'POST',
      headers: {
        Authorization: 'Bearer ' + token,
        'Content-type': 'application/json',
      },
      body: JSON.stringify({media_id}), //{media_id: media_id params -> reduced}
    };
    // TODO: return the data
    return await fetchData<MessageResponse>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/likes',
      options,
    );
  };

  const deleteLike = async (like_id: number, token: string) => {
    // TODO: Send a DELETE request to /likes/:like_id with the token in the Authorization header.
    const options = {
      method: 'DELETE',
      headers: {
        Authorization: 'Bearer ' + token,
      },
    };
    // return the data
    return await fetchData<MessageResponse>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/likes/' + like_id,
      options,
    );
  };

  // Tykkäyksien määrä
  const getCountByMediaId = async (media_id: number) => {
    // Send a GET request to /likes/count/:media_id to get the number of likes.
    return await fetchData<{count: number}>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/likes/count/' + media_id,
    );
  };

  const getUserLike = async (media_id: number, token: string) => {
    // Send a GET request to /likes/bymedia/user/:media_id to get the user's like on the media. -> tarvitaan options koska haetaan tietyn käyttäjän
    const options = {
      method: 'GET',
      headers: {
        Authorization: 'Bearer ' + token,
      },
    };
    return await fetchData<Like>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/likes/bymedia/user/' + media_id,
      options,
    );
  };

  return {postLike, deleteLike, getCountByMediaId, getUserLike};
};

const useComment = () => {
  const {getUserById} = useUser();
  // iplement media/comments resource API connections

  // lähetä kommentti
  const postComment = async (
    comment_text: string,
    media_id: number,
    token: string,
  ) => {
    const options = {
      method: 'POST',
      headers: {
        Authorization: 'Bearer ' + token,
        'Content-type': 'application/json',
      },
      body: JSON.stringify({media_id, comment_text}),
    };
    // TODO: return the data
    return await fetchData<MessageResponse>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/comments',
      options,
    );
  };

  const getCommentsByMediaId = async (media_id: number) => {
    // Send a GET request to /comments/bymedia/:media_id to get the comments.
    const comments = await fetchData<Comment[]>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/comments/bymedia/' + media_id,
    );
    // Send a GET request to auth api and add username to all comments
    const commentsWithUsername = await Promise.all<
      Comment & {username: string}
    >(
      comments.map(async (comment) => {
        const user = await getUserById(comment.user_id);
        return {...comment, username: user.username};
      }),
    );
    return commentsWithUsername;
  };

  // kommenttien määrä
  const getCommentCountByMediaId = async (id: number) => {
    return await fetchData<{count: number}>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/comments/count/' + id,
    );
  };

  return {postComment, getCommentsByMediaId, getCommentCountByMediaId};
};

// RATINGS

const useRating = () => {
  // ratingit per media
  const getAverageRating = async (id: number) => {
    return await fetchData<{average: number}>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/ratings/average/' + id,
    );
  };

  return {getAverageRating};
};

// TAGS

const useTag = () => {
  // all tags
  const getAllTags = async () => {
    return await fetchData<Tag[]>(process.env.EXPO_PUBLIC_MEDIA_API + '/tags');
  };
  // all tags per media
  const getTagsByMediaId = async (media_id: number) => {
    return await fetchData<TagResult[]>(
      process.env.EXPO_PUBLIC_MEDIA_API + '/tags/bymedia/' + media_id,
    );
  };
  return {getAllTags, getTagsByMediaId};
};

export {
  useMedia,
  useAuthentication,
  useUser,
  useComment,
  useFile,
  useLike,
  useRating,
  useTag,
};
